In [1]:
import tensorflow as tf
import keras
print(tf.__version__)
print(keras.__version__)

2024-04-11 21:48:22.571553: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-11 21:48:22.616480: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-11 21:48:23.330806: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.13.1
2.13.1


In [2]:
#Make sure the GPU is available. 
import tensorflow as tf
device_name = tf.test.gpu_device_name()

2024-04-11 21:48:24.858733: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 21:48:24.860420: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 21:48:24.861999: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [3]:
#Make sure the GPU is available. 
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


2024-04-11 21:48:27.538437: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 21:48:27.539921: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-04-11 21:48:27.541354: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [4]:
import segmentation_models_3D as sm


Segmentation Models: using `tf.keras` framework.


In [5]:
from skimage import io
from patchify import patchify, unpatchify
import numpy as np
from matplotlib import pyplot as plt
from keras import backend as K
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

In [6]:
num_epochs = 1500


vista_crop_dict = { 0:'NA' , 1: 'ALFALFA', 2: 'BEET', 3: 'CLOVER', 4: 'FLAX', 5: 'FLOWERING_LEGUMES', 6: 'FLOWERS', 7: 'FOREST', 8: 'GRAIN_MAIZE', 9: 'GRASSLAND', 10: 'HOPS', 11: 'LEGUMES', 12: 'NA', 13: 'PERMANENT_PLANTATIONS', 14: 'PLASTIC', 15: 'POTATO', 16: 'PUMPKIN', 17: 'RICE', 18: 'SILAGE_MAIZE', 19: 'SOY', 20: 'SPRING_BARLEY', 21: 'SPRING_OAT', 22: 'SPRING_OTHER_CEREALS', 23: 'SPRING_RAPESEED', 24: 'SPRING_RYE', 25: 'SPRING_SORGHUM', 26: 'SPRING_SPELT', 27: 'SPRING_TRITICALE', 28: 'SPRING_WHEAT', 29: 'SUGARBEET', 30: 'SUNFLOWER', 31: 'SWEET_POTATOES', 32: 'TEMPORARY_GRASSLAND', 33: 'WINTER_BARLEY', 34: 'WINTER_OAT', 35: 'WINTER_OTHER_CEREALS', 36: 'WINTER_RAPESEED', 37: 'WINTER_RYE', 38: 'WINTER_SORGHUM', 39: 'WINTER_SPELT', 40: 'WINTER_TRITICALE', 41: 'WINTER_WHEAT'}

In [7]:
labels = np.load('/home/luser/stelar_3d/storage/full_mast/vista_labes_aligned.npy').astype(np.uint8)


In [8]:
unique_elements, element_counts = np.unique(labels, return_counts=True)
unique_elements, element_counts

(array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 18,
        19, 20, 21, 23, 27, 28, 30, 32, 33, 34, 35, 36, 37, 40, 41],
       dtype=uint8),
 array([61307860,  1106626,   146323,   143701,     7143,     3025,
          205807,  4566575,  7400638,       72,   924407,   458142,
         8427517,    18792,    60594,     9681,   676780,  1376503,
           31686,     6077,     2623,     2499,     8633,  3142945,
         1564605,   791290,    87956,     1016,  1003306,    16938,
          444574,  6095670]))

In [23]:
# consider ALFALFA

for ele in unique_elements:
    print(ele)

0
1
2
3
4
5
7
8
9
10
11
12
13
14
15
16
18
19
20
21
23
27
28
30
32
33
34
35
36
37
40
41


In [25]:
box_count = 0

for ele in unique_elements:
    x_inds = np.where(labels==ele)[0]
    y_inds = np.where(labels==ele)[1]

    unique_x_inds = np.unique(x_inds)
    unique_y_inds = np.unique(y_inds)

    unique_x_quotient_inds = (unique_x_inds)//64
    unique_unique_x_quotient_inds = np.unique(unique_x_quotient_inds)


    unique_y_quotient_inds = (unique_y_inds)//64
    unique_unique_y_quotient_inds = np.unique(unique_y_quotient_inds)

    box_bottom_left_x = unique_unique_x_quotient_inds*64
    box_bottom_left_y = unique_unique_y_quotient_inds*64


    print("box_bottom_left_x, box_bottom_left_y", box_bottom_left_x, box_bottom_left_y)

    print("len(box_bottom_left_x), len(box_bottom_left_y)", len(box_bottom_left_x), len(box_bottom_left_y))

    box_count += len(box_bottom_left_x)*len(box_bottom_left_y)
print("box_count", box_count)

box_bottom_left_x, box_bottom_left_y [   0   64  128  192  256  320  384  448  512  576  640  704  768  832
  896  960 1024 1088 1152 1216 1280 1344 1408 1472 1536 1600 1664 1728
 1792 1856 1920 1984 2048 2112 2176 2240 2304 2368 2432 2496 2560 2624
 2688 2752 2816 2880 2944 3008 3072 3136 3200 3264 3328 3392 3456 3520
 3584 3648 3712 3776 3840 3904 3968 4032 4096 4160 4224 4288 4352 4416
 4480 4544 4608 4672 4736 4800 4864 4928 4992 5056 5120 5184 5248 5312
 5376 5440 5504 5568 5632 5696 5760 5824 5888 5952 6016 6080 6144 6208
 6272 6336 6400 6464 6528 6592 6656 6720 6784 6848 6912 6976 7040 7104
 7168 7232 7296 7360 7424 7488 7552 7616 7680 7744 7808 7872 7936 8000
 8064 8128 8192 8256 8320 8384 8448 8512 8576 8640 8704 8768 8832 8896
 8960 9024 9088 9152 9216 9280 9344 9408 9472 9536 9600 9664 9728 9792
 9856 9920 9984] [   0   64  128  192  256  320  384  448  512  576  640  704  768  832
  896  960 1024 1088 1152 1216 1280 1344 1408 1472 1536 1600 1664 1728
 1792 1856 1920 1984 20

In [18]:
box_bottom_left_x, box_bottom_left_y

(array([ 320,  448, 3136, 3200, 4480, 4544, 6336, 6400, 9088]),
 array([2688, 2752, 3776, 5056, 5120, 5184, 5248, 9344, 9408, 9856]))

In [13]:
#box origins

unique_unique_x_quotient_inds * 64 , unique_unique_y_quotient_inds * 64

(array([ 320,  448, 3136, 3200, 4480, 4544, 6336, 6400, 9088]),
 array([2688, 2752, 3776, 5056, 5120, 5184, 5248, 9344, 9408, 9856]))

In [14]:
#box ends

unique_unique_x_quotient_inds * 64 + 64, unique_unique_y_quotient_inds * 64 + 64

(array([ 384,  512, 3200, 3264, 4544, 4608, 6400, 6464, 9152]),
 array([2752, 2816, 3840, 5120, 5184, 5248, 5312, 9408, 9472, 9920]))